apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: zhalgas715/to-do-react:latest 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
